import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "./_Components/Navbar/Navbar";
import Banner from "./_Components/Home/Banner";

const figtree = Figtree({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ahmed Ekramy | Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.className} `}>
        <Navbar />
        <Banner />
        {children}
      </body>
    </html>
  );
}
